apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-tunnel
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ssh
      tier: tunnel
  template:
    metadata:
      labels:
        app: ssh
        tier: tunnel
    spec:
      containers:
        - image: nicholasxuu/openssh-server
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 22
              protocol: TCP
          resources:
            limits:
              cpu: 20m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 15Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
