apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-tunnel
  namespace: abc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ssh
      tier: tunnel
  template:
    metadata:
      labels:
        app: ssh
        tier: tunnel
    spec:
      containers:
      - envFrom:
          - secretRef:
            name: tunnel-secrets
        image: linuxserver/openssh-server:amd64-latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 2222
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 15Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
