# MySQL is not used in this project, 
# but keeping this file here if mysql is needed.
FROM mysql:5.6

# needed in docker for mac, when placing mysql db data files in volumn.
#RUN usermod -u 1000 mysql
#RUN mkdir -p /var/run/mysqld
#RUN chmod -R 777 /var/run/mysqld